apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.name }}
  labels:
    app: ${{ values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.name }}
  strategy: {}
  template:
    metadata:
      labels:
        app: ${{ values.name }}
    spec:
      containers:
      #User repourl owner instead of iron87
      - image: ghcr.io/iron87/${{ values.name }}:latest
        name: ${{ values.name }}
